server:
  port: 80
spring:
  datasource:
    username: root
    password: 311252
    url: jdbc:mysql://localhost:3306/sms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 127.0.0.1
#    port: 6379
mybatis:
  type-aliases-package: com.sms.pojo
  mapper-locations: classpath:mapper/*.xml
